config/routes.rb
Rails.application.routes.draw do
  resources :doctors
  resources :patients
  resources :generate_appointments
  resources :dashboard do 
    collection do 
      get :available_doctors
    end
  end
  root to: "dashboard#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many :patients, through: :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :doctors, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
def index;end
  def available_doctors
    #first way
    @doctors = Doctor.left_outer_joins(:appointments).where(appointments: {doctor_id: nil})
    #second_way
    # @doctor = Doctor.all - Doctor.joins(:appointments)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: %i[ show edit update destroy ]

  # GET /doctors or /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1 or /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors or /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully created." }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1 or /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully updated." }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1 or /doctors/1.json
  def destroy
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to doctors_url, notice: "Doctor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doctor_params
      params.require(:doctor).permit(:name, :speaclist)
    end
end

app/controllers/generate_appointments_controller.rb
class GenerateAppointmentsController < ApplicationController
  before_action :set_generate_appointment, only: %i[ show edit update destroy ]

  # GET /generate_appointments or /generate_appointments.json
  def index
    @generate_appointments = Appointment.all
  end

  # GET /generate_appointments/1 or /generate_appointments/1.json
  def show
  end

  # GET /generate_appointments/new
  def new
    @generate_appointment = Appointment.new
  end

  # GET /generate_appointments/1/edit
  def edit
  end

  # POST /generate_appointments or /generate_appointments.json
  def create
    @generate_appointment = Appointment.new(generate_appointment_params)

    respond_to do |format|
      if @generate_appointment.save
        format.html { redirect_to generate_appointment_url(@generate_appointment), notice: "Generate appointment was successfully created." }
        format.json { render :show, status: :created, location: @generate_appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @generate_appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /generate_appointments/1 or /generate_appointments/1.json
  def update
    respond_to do |format|
      if @generate_appointment.update(generate_appointment_params)
        format.html { redirect_to generate_appointment_url(@generate_appointment), notice: "Generate appointment was successfully updated." }
        format.json { render :show, status: :ok, location: @generate_appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @generate_appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generate_appointments/1 or /generate_appointments/1.json
  def destroy
    @generate_appointment.destroy

    respond_to do |format|
      format.html { redirect_to generate_appointments_url, notice: "Generate appointment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_generate_appointment
      @generate_appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def generate_appointment_params
      params.require(:appointment).permit(:doctor_id, :patient_id, :appointment_datetime)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/generate_appointments_helper.rb
module GenerateAppointmentsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/dashboard/available_doctors.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Speaclist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.speaclist %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/dashboard/index.html.erb
<h1>Welcome</h1>
<%= link_to "Doctors", doctors_path-%> <br><br>
<%= link_to "Patients", patients_path-%> <br><br>
<%= link_to "Appointment", generate_appointments_path-%> <br><br>
<%= link_to "Available doctors", available_doctors_dashboard_index_path-%>

app/views/doctors/_form.html.erb
<%= form_with(model: doctor) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
        <% doctor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :speaclist %>
    <%= form.text_field :speaclist %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Speaclist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.speaclist %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Speaclist:</strong>
  <%= @doctor.speaclist %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/generate_appointments/_form.html.erb
<%= form_with(model: generate_appointment, method: :POST, url: generate_appointments_path) do |form| %>
  <% if generate_appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(generate_appointment.errors.count, "error") %> prohibited this generate_appointment from being saved:</h2>

      <ul>
        <% generate_appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :Doctor %>
    <%= form.select :doctor_id, options_for_select(Doctor.all.map{|doc| [doc.name, doc.id]})-%>
  </div>
  <div class="field">
    <%= form.label :Patient %>
    <%= form.select :patient_id, options_for_select(Patient.all.map{|doc| [doc.name, doc.id]})-%>
  </div>

  <div class="field">
    <%= form.label :Date_time %>
    <%= form.datetime_local_field :appointment_datetime %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/generate_appointments/edit.html.erb
<h1>Editing Generate Appointment</h1>

<%= render 'form', generate_appointment: @generate_appointment %>

<%= link_to 'Show', @generate_appointment %> |
<%= link_to 'Back', generate_appointments_path %>

app/views/generate_appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Generate Appointments</h1>

<table>
  <thead>
    <tr>      
      <th>Doctor Name</th>
      <th>Patient Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @generate_appointments.each do |generate_appointment| %>
      <tr>
        <td><%= generate_appointment.doctor.name %></td>
        <td><%= generate_appointment.patient.name %></td>
        <td><%= link_to 'Show', generate_appointments_path %></td>
        <td><%= link_to 'Edit', edit_generate_appointment_path(generate_appointment) %></td>
        <td><%= link_to 'Destroy', generate_appointments_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Generate Appointment', new_generate_appointment_path %>

app/views/generate_appointments/new.html.erb
<h1>New Generate Appointment</h1>

<%= render 'form', generate_appointment: @generate_appointment %>

<%= link_to 'Back', generate_appointments_path %>

app/views/generate_appointments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_generate_appointment_path(@generate_appointment) %> |
<%= link_to 'Back', generate_appointments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appoitment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>